title: ChatAssist by Ajay
description: A lightweight, privacy-first WordPress chat widget plugin.
url: "https://ackm04.github.io"
baseurl: "/chatassist"

plugins:
  - jekyll-seo-tag

markdown: kramdown
